// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmefouuhxoyztxyxhvvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtZWZvdXVoeG95enR4eXhodnZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODk1MDEsImV4cCI6MjA2NjI2NTUwMX0.y7-Hnq524K43wCgRS-ciSiFCwdlLvC-n3h41CI837BI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);